### ISSUE TITLE
A question about run run_mvtec.py

### ISSUE THREAD

**Issue by renqiqi** [liznerski/fcdd#13]
When I ran python runner/run_mvtec.py, I found that there was no training but directly printed in the terminal: plotting many ROC for completed classes up to [0,...,14], I didn’t find the pictures whcih plotting in the file related directory. 
Can you give me some suggestions? thank you very much.

**Comment by liznerski** [comment]
Hi. Unfortunately, I am unable to reproduce this. 
It doesn't show any error message? 
Can you provide the full print?
Did you use the default parameters and original code?
What OS did you use?
You're sure you didn't set the number of epochs to 0?
If epochs are set to 0, the script will skip both training and testing, so there are no plots or pictures to be found.

**Comment by renqiqi** [comment]
OS：Ubuntu 16.04 LTS
I didn‘’t modify the code, just added MVTec AD datasets.
Then ran: python runner/run_mvtec.py
Directly printed in the terminal：
plotting many ROC for completed classes up to 0
plotting many ROC for completed classes up to 1
plotting many ROC for completed classes up to 2
plotting many ROC for completed classes up to 3
plotting many ROC for completed classes up to 4
plotting many ROC for completed classes up to 5
plotting many ROC for completed classes up to 6
plotting many ROC for completed classes up to 7
plotting many ROC for completed classes up to 8
plotting many ROC for completed classes up to 9
plotting many ROC for completed classes up to 10
plotting many ROC for completed classes up to 11
plotting many ROC for completed classes up to 12
plotting many ROC for completed classes up to 13
plotting many ROC for completed classes up to 14

So do I need to modify the config of run_mvtec.py？

**Comment by liznerski** [comment]
What do you mean by "added MVTec AD datasets"? Did you add it on your own?  If you did, just remove it and run the code again. It should work.
The code automatically downloads MVTec and processes it to the required format. Adding it manually won't work unless you put it in the form that the program expects.

**Comment by renqiqi** [comment]
If directly run: python runners/run_mvtec.py, the program will download mvtec_anomaly_detection.tar.xz to the folder: ./data/datasets/mvtec/
So I directly put the previously downloaded dataset into this path, and then an error occurs when running the program.
I don’t think there should be a problem with putting data like this

**Comment by liznerski** [comment]
That should work, yes. It should start extracting the archive. The first print should be something like `Extracting .../data/datasets/mvtec/mvtec_anomaly_detection.tar.xz to /tmp/tmp568thc0g`, which is to be found in [this line](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/mvtec_base.py#L272),  Since the print is missing, I assume there is an error thrown beforehand, directly jumping to [this line](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/bases.py#L227). But there should be an error message. Can you try to track down where the error occurs? As said, I am unable to reproduce this. 

Also, /data/datasets/mvtec/ is empty apart from the archive?

**Comment by renqiqi** [comment]
I am sure the folder /data/datasets/mvtec/ is empty apart from the archive.
Thank you for your reply. 
I just want to use your model for comparative experiments. Due to time constraints, I am afraid that I cannot further study the cause of the error.
When I have time in the future, I will study your model. 
Thank you again for your work.
