### ISSUE TITLE
Syntax Error  From __init__.py

### ISSUE THREAD

**Issue by SHANK885** [liznerski/fcdd#20]
Can you please tell me why this error is coming out?
![error_log](https://user-images.githubusercontent.com/36559699/134455471-f63a2e9a-b402-4fc4-86c3-3d8e09088b70.png)

**Comment by liznerski** [comment]
Hi. Which python version are you using? I think that this type of variable annotation is only supported from python 3.6 onwards.

**Comment by SHANK885** [comment]
Solved the issue by updating the python version. Thanks
