### ISSUE TITLE
How to pip install FCDD ?

### ISSUE THREAD

**Issue by danielsoy** [liznerski/fcdd#23]
Hey there!

I would like to run the windows version of mvtec.py.

But i could not install FCDD after installing the requirements , and got all this errors
when mvtec.py tries to access **bases.py**

from fcdd.runners.argparse_configs import DefaultConfig
from fcdd.training.setup import trainer_setup
from fcdd.training.super_trainer import SuperTrainer
from fcdd.util.logging import plot_many_roc, time_format
from fcdd.util.metrics import mean_roc

Which is the right pip command to install it?

In the installation instructions says: **pip install... (nothing)**

Thanks you so much!

**Comment by liznerski** [comment]
Hey. 
The installation says `pip install .`, which is different from pip install nothing.
The dot refers to the current working directory, which should be the `python` directory (https://github.com/liznerski/fcdd/tree/master/python), as mentioned in the readme. So either you change your directory to this one, or type `pip install path/to/my/python/directory/`.
