### ISSUE TITLE
Enlarging dataset option for custom datasets

### ISSUE THREAD

**Issue by GreatScherzo** [liznerski/fcdd#28]
I was wondering if there is an enlarging option for custom datasets for 
users to try, such as the one used for MVTec dataset.

I'm currently training by setting the epoch to 2000 
and also using the same training parameters used for MVTec dataset 
to get the same performance, but it sure takes some time.

Thank you for taking your time!

**Comment by liznerski** [comment]
It's not implemented, but it requires little change. 
For MVTec, enlarging boils down to a few lines: [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/mvtec_base.py#L91).

Adding a similar things to the [ImageFolderDataset](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L211) should be easy. 
Something like
```
self.samples = self.samples * 10 
self.anomaly_labels = self.anomaly_labels * 10
```

**Comment by GreatScherzo** [comment]
Welp, that's terribly simple!
I made a quick change to the ImageFolderDataset and made a PR if you want to implement it.
#29 

Cheers!
