### ISSUE TITLE
Disabling test phase after training is completed

### ISSUE THREAD

**Issue by GreatScherzo** [liznerski/fcdd#31]
Hello again, @liznerski !

I want to add an option that allows the user to disable the usage of testing data, 
and only do training when training a custom dataset.

Is that even possible? 
If it is, what are the places that I should be editing to be able to do so?

Thanks, once again!

**Comment by liznerski** [comment]
Hey again,
the [BaseRunner](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/bases.py#L106) invokes the trainer's train and test routines. There's already a variable determining whether to test or not ([here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/bases.py#L82)). You can simply add another argument to the Config ([here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_custom.py#L36)), like: ``parser.add_argument("--no-test", action="store_false", dest='test')```. The BaseRunner will parse the arguments in its init and you can just set the variable according to the argument in the init of the BaseRunner.

**Comment by GreatScherzo** [comment]
Thank you very much @liznerski !
I was able to add the argument to cancel the test phase.

Sorry for the late reply, I had some business to attend
