### ISSUE TITLE
How to  set run_custom parameters?

### ISSUE THREAD

**Issue by Stephenhua** [liznerski/fcdd#34]
I run run_custom.py, I set dataset by this way:
<img width="653" alt="dataSet" src="https://user-images.githubusercontent.com/41442321/166673130-e9fb658b-973c-4477-842e-83130c904d01.png">
In test file  , it is include normal and annormal file, as mtevc datset structure.

then，I set parameters by this way:
    
parser.set_defaults(
            batch_size=16 , acc_batches = 8, supervise_mode='unsupervised',preproc='aug1',
            gauss_std=12, epochs=500, weight_decay=1e-4,
            quantile=0.99, net='FCDD_CNN224_VGG_F', dataset='custom', noise_mode='confetti'
        )
other parameters set default.

when I trained finished , the heatmap seems is not  correct .
the heatmap_paper_local_lbl1.png 
![image](https://user-images.githubusercontent.com/41442321/166673636-6385fc4a-b911-4e08-9ed3-f4b435d08e9a.png)

the heatmap_paper_local_lbl0.png 
![image](https://user-images.githubusercontent.com/41442321/166673766-de178bcd-0efd-4231-8831-515553a65384.png)

the heatmaps_paper_global_lbl1.png
![image](https://user-images.githubusercontent.com/41442321/166673877-7bff4a29-d306-40b0-9a46-37894f744476.png)

the heatmaps_paper_global_lbl0.png
![image](https://user-images.githubusercontent.com/41442321/166673960-e59aeb8b-a38f-44e2-b4bb-4da5bdbd20b2.png)

the train_heatmaps_global.png
![image](https://user-images.githubusercontent.com/41442321/166674098-4f7ee126-17e1-4e80-bb69-cbb5d2e187df.png)

the heatmap_global.png
![image](https://user-images.githubusercontent.com/41442321/166674220-97aa48ac-281c-4037-8edb-690fc3fa7fd2.png)

I am not clear that which parameters lead to this result. Looking forward your replying. If you have time to write a  detail Markdown about how to run run_custom.py, Thank you very much.

**Comment by liznerski** [comment]
Hey. There is a dedicated runner for the MVTec-AD dataset ([here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_mvtec.py)). This runner is tested. Theoretically, you should also be able to produce the same results with the custom runner, but then you need to make sure to set all parameters correctly (including, e.g., augmentations, which differ in the custom runner). However, there is no need to do so. Just use the dedicated runner.
