### ISSUE TITLE
Disabling log data output except snapshot.pt

### ISSUE THREAD

**Issue by GreatScherzo** [liznerski/fcdd#38]
Hi again @liznerski !

I wish to edit the log data output and leave only snapshot.pt as an output.
Where should I be editing to do so?

Once again, thank you very much for taking your time!

**Comment by liznerski** [comment]
Btw, feel also free to write me a [mail](mailto:liznerski@cs.uni-kl.de).

**Comment by GreatScherzo** [comment]
Thank you for your answer! I'll try creating that variable that disables other log outputs. 
I'll close this issue if there's no problem whatsoever.

I'll be sure to drop a mail to you anytime soon!

**Comment by GreatScherzo** [comment]
I was able to do it without any major problems.
As suggested above, I added a variable that disables every saving method (except saving the snapshot) in the Logger class if false.

Thank you!
