### ISSUE TITLE
Can I run it on a cpu?

### ISSUE THREAD

**Issue by francesco28597** [liznerski/fcdd#52]
Hi,
I hope this is not a silly question, I am quite unexperienced on the field.
I'm trying to use the network on a laptop without any cuda GPUs, and it seems not to be working. Shouldn't it run on the cpu as well?

**Comment by liznerski** [comment]
Hey. No worries. The code can run on the CPU, but it doesn't do this automatically. You need to specify this via the program argument `--cpu`. That being said, training a complete network on the CPU only is going to take a very long time...

**Comment by francesco28597** [comment]
Worked fine. Thank you!
