### ISSUE TITLE
The output of the model is often nan, what can be done to avoid the output of nan. Also because of the output of nan, the roc indicator cannot be calculated, can you tell me?thank you.

### ISSUE THREAD

**Issue by 18894269590** [liznerski/fcdd#59]
[wrong](https://imgur.com/a/4ayEdEV)

**Comment by liznerski** [comment]
Please provide more details. Did you change the code? What configuration/dataset/... did you use? You can upload images directly to git. There are a lot of nice guides that describe how to write a good github issue: https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
