### ISSUE TITLE
Rename online_superviser and offline_superviser

### ISSUE THREAD

**Issue by GabiThume** [liznerski/fcdd#6]
Hi! Thank you for providing the FCDD implementation!
In your last commit (https://github.com/liznerski/fcdd/commit/e8d71d0b7e90487a238215aa8001144109da2793), you renamed `superviser` to `supervisor` but the filename and class name of `online_superviser.py` and filename `offline_superviser.py` should be renamed too, otherwise the runners won't work.

**Comment by liznerski** [comment]
Thanks for reporting! Must have slipped out the commit. Solved with b37835134641ddbd25ba295d218075cd1686aaeb.
