### ISSUE TITLE
Image level AUC-ROC for MV-Tech dataset

### ISSUE THREAD

**Issue by alfons06** [liznerski/fcdd#62]
Dear Liznerski,
I am unable to find information about image-level AUC-ROC in your work.
Do you have any reliable information on this?

Thank you in advance

**Comment by liznerski** [comment]
Hi. We focused on using MVTec-AD as a means to evaluate the heatmaps. I think the AuROC at image level was a bit worse, maybe about 80%. You can use the code to compute precise results.
