### ISSUE TITLE
Error running custom.py using semi-supervised mode with multiple classes

### ISSUE THREAD

**Issue by thy789** [liznerski/fcdd#64]
Hi liznerski, thanks for the great work!

I'm trying to train a custom dataset (with 5 classes) with the semi-supervised mode where i provide the ground truth maps for both train and test sets. I have been facing an error that says there are inconsistent number of samples.
I structured my dataset according to this format:
![image](https://github.com/liznerski/fcdd/assets/143565311/6569362b-10d0-4005-9669-d4656217add5)

The error i got:
![image](https://github.com/liznerski/fcdd/assets/143565311/cb01e5c6-f712-4093-9119-e619b105bb42)

I printed their shapes to understand the error:
![image](https://github.com/liznerski/fcdd/assets/143565311/21982a1c-97c7-45f2-bd45-564a12596fd3)

I believe the error is due to the 'gtmaps' taking the total number of test samples from all 5 classes (172 normal + 174 anomalous) while the 'ascores' is only getting the test samples of the first class (30 normal + 72 anomalous). When i tried training only 1 class, the training completed successfully without any errors.

I assume the 'fcdd.datasets.image_folder_gtms.ImageFolderDatasetGTM.get_original_gtmaps_normal_class' is the root cause of this error. Any suggestions on how to fix this?
Thanks in advance.

**Comment by liznerski** [comment]
Hi. Good catch, thanks for the detailed bug report. Fixed with commit [4fa8502](https://github.com/liznerski/fcdd/commit/4fa850215792b5f4a3405151e30127a5b67dc3b6).

**Comment by thy789** [comment]
Hey, thanks for the fix! It works fine now.
