### ISSUE TITLE
Train fcdd with rectangular image

### ISSUE THREAD

**Issue by thy789** [liznerski/fcdd#68]
Hi liznerski,

I'm trying to train a custom dataset. I wonder if I could use rectangular images to train fcdd. I tried using a rectangular size and faced an assertion error in this line: [https://github.com/liznerski/fcdd/blob/97400156cd06604a2fa0189bee3dec5f65966f02/python/fcdd/models/bases.py#L162C1-L162C65](url)

Do I simply remove the "in_shape[1] == in_shape[2]" portion to continue training with rectangular image or is there any other changes to make?

Thanks.

**Comment by liznerski** [comment]
Hi!

In principle FCDD can handle this. However, the code expects the images to be square. I think the only issue is that the [ReceptiveNet](https://github.com/liznerski/fcdd/blob/master/python/fcdd/models/bases.py#L210) just tracks the height of the input. The receptive upsampling would thus not produce images of correct resolution. As long as you still use square convolutions, I think the rest should be fine.

Cheers.
