### ISSUE TITLE
Normal GT maps also contains the red spots

### ISSUE THREAD

**Issue by NM0727** [liznerski/fcdd#70]
Hello ,
The normal gt maps also contains the red spots which is resulting in the false positives during testing.Can you please help me in letting know the ideas in order to reduce them ? 
Have already used increasing the quantile hyper parameter. 
Thanks in advance.

**Comment by liznerski** [comment]
Hi. Without further information about your application, this is hard to answer. In general, as with all ML models, the performance relies on the quantity and quality of data. For FCDD it's also important to have suitable OE data. We have published a paper on what can be learned from OE and what kind of OE is needed (https://arxiv.org/abs/2205.11474). Maybe this helps?
