### ISSUE TITLE
MVTec-AD with oe-limit

### ISSUE THREAD

**Issue by layadas** [liznerski/fcdd#72]
I am trying to reproduce the results of Table 2 in the paper (MvTec-AD gtmap-auc) with one anomalous image in the self-supervised setting (last column of Table 2). I am using the following command, as suggested in the repository page:
```python runners/run_mvtec.py --supervise-mode noise --noise-mode mvtec_gt --oe-limit 1 ```

The generated `ds_preview.png` still shows 3 anomalous images instead of 1. I have tried running this multiple times, on different computers, and it always picks 3 anomalies instead of 1.

Here is a sample `ds_preview.png` generated for the above command:
![ds_preview](https://github.com/liznerski/fcdd/assets/62447733/f82a7e1f-3109-40dc-b40c-983e6ad391b9)

I am not sure why this is happening. I went through the code where `oe-limit` is used in [outlier_exposure/mvtec.py](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/outlier_exposure/mvtec.py#L54), but I am cannot see why this might be happening.

Thank you in advance for your help.

**Comment by liznerski** [comment]
Hey. This behavior is intended. For MVTec-AD, we use "[...] just one true anomalous sample per defect type at random and add it to the training set. This results in only 3-8 anomalous training samples." (FCDD paper). In the code, there is a parameter ``limit_per_anomaly`` ([here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/outlier_exposure/mvtec.py#L17)), which you can set to False to overall pick 1 random anomaly instead.

**Comment by layadas** [comment]
Thank you for the clarification.
