### ISSUE TITLE
Could we use Grad-CAM to get a heatmap?

### ISSUE THREAD

**Issue by Kokoing123** [liznerski/fcdd#9]
hi, I'm a beginner, this question may be not professional，but it puzzles me。it seems that Grad-CAM can also get class heatmap, why not use it to visualize abnormal information?

**Comment by liznerski** [comment]
Hey. You can use Grad-CAM to get an "abnormal class heatmap"; it's another gradient-based explanation method. However, you lose some advantages of FCDD, as FCDD's explanations are directly tied to the anomaly score. Feel free to try it, though.

**Comment by Kokoing123** [comment]
okay, thank you for your patient answer.
